version: 0.0
os: linux

files:
  - source: /scripts
    destination: /home/ec2-user/chat
    
permissions:
  - object: scripts
    pattern: "**"
    owner: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: root
