# Generated by Django 3.1 on 2020-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=60)),
                ("message", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
