# Generated by Django 3.1 on 2020-11-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20201104_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='censored_message',
            field=models.TextField(default='*** Censored Message ***'),
        ),
        migrations.AddField(
            model_name='chat',
            name='modified_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('normal', 'normal'), ('modified', 'modified'), ('censored', 'censored')], default='normal', max_length=60),
        ),
    ]
