# Generated by Django 3.1 on 2020-11-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20201104_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='modified_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
