version: '3'
services:
  web:
    image: 601498516328.dkr.ecr.us-east-1.amazonaws.com/arquitectura:latest
    env_file: /home/ec2-user/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "80:8000"
  
  redis:
    image: "redis:alpine"